"""Outbound contracts; application code owns these interfaces."""

from typing import Callable, Protocol


class EnrichmentStore(Protocol):
    def rows(self, table: str, **filters) -> list[dict]: ...
    def save(self, table: str, records: list[dict]) -> None: ...
    def update_request(self, request_id: str, change: Callable) -> dict: ...
    def save_owned(self, table: str, records: list[dict], owner: dict) -> None: ...


class PaperCatalog(Protocol):
    def queries(self) -> list[dict]: ...
    def capture(self, query_id: str) -> tuple[dict, int, int]: ...
    def page(
        self, query_id: str, snapshot: int, cursor: str, limit: int
    ) -> list[dict]: ...


class WorkSource(Protocol):
    def lookup(self, identifier: str, before_request: Callable) -> dict | None: ...
