"""Outbound ports owned by the PubMed application."""

from collections.abc import Callable
from typing import Protocol


class PublicationStore(Protocol):
    def rows(self, table: str, **filters) -> list[dict]: ...
    def save(self, table: str, records: list[dict]) -> None: ...
    def claim(self, request_id: str, run_id: str) -> dict: ...
    def update_schedule(
        self, schedule_id: str, change: Callable[[dict], dict]
    ) -> dict: ...
    def delete_schedule(self, schedule_id: str) -> None: ...


class LiteratureSource(Protocol):
    def search(self, parameters: dict) -> tuple[int, list[dict]]: ...
    def download(self, pmcid: str) -> tuple[bytes, dict]: ...


class ArtifactStorage(Protocol):
    def put_object(self, prefix: str, key: str, content: bytes) -> None: ...
    def get_object(self, prefix: str, key: str) -> bytes: ...
