"""Outbound ports owned by the PubMed application."""

from collections.abc import Callable
from typing import Protocol


class PublicationStore(Protocol):
    def browse_papers(self, filters: dict) -> tuple[int, list[dict]]: ...
    def rows(self, table: str, **filters) -> list[dict]: ...
    def recent_requests(self, limit: int = 100) -> list[dict]: ...
    def members(
        self, query_id: str, pmids: list[str] | None = None, limit: int = 1001
    ) -> list[dict]: ...
    def member_count(self, query_id: str) -> int: ...
    def rows_for_pmids(self, table: str, pmids: list[str]) -> list[dict]: ...
    def save(self, table: str, records: list[dict]) -> None: ...
    def claim(self, request_id: str, run_id: str) -> dict: ...
    def update_schedule(
        self, schedule_id: str, change: Callable[[dict], dict]
    ) -> dict: ...
    def create_request(self, row: dict) -> dict: ...
    def update_backfill(
        self, backfill_id: str, change: Callable[[dict], dict]
    ) -> dict: ...
    def delete_schedule(self, schedule_id: str) -> None: ...


class LiteratureSource(Protocol):
    def search(self, parameters: dict) -> tuple[int, list[dict]]: ...
    def search_ids(
        self,
        parameters: dict,
        lower: int | None = None,
        upper: int | None = None,
        limit: int = 200,
    ) -> tuple[int, list[str]]: ...
    def summaries(self, ids: list[str]) -> list[dict]: ...
    def download(self, pmcid: str) -> tuple[bytes, dict]: ...


class ArtifactStorage(Protocol):
    def put_object(self, prefix: str, key: str, content: bytes) -> None: ...
    def get_object(self, prefix: str, key: str) -> bytes: ...
